### ISSUE TITLE
Remounting story with withRouter decorator gives "two children with the same key" error

### ISSUE THREAD

**Issue by ningxie1991** [JesusTheHun/storybook-addon-react-router-v6#23] opened 2023-03-23 08:01 UTC
I have a story using the withRouter decorator. When I change some control props and click the remount addon button to reload the story, I get the below warning/error. 

This is the remount button from the addon essentials:

![image](https://user-images.githubusercontent.com/3387698/227140018-538eb9de-cca1-4480-9511-62652f337ff9.png)

I also have a theme switcher addon that remounts the story by updating the story key every time a theme is chosen. This flow also triggers the same error from the react-router-v6 addon.

![image](https://user-images.githubusercontent.com/3387698/227140329-a08d242f-a7ac-436b-9c42-23f145e2fdc1.png)

Warning:

![image](https://user-images.githubusercontent.com/3387698/227139662-ed7ff511-43b5-473a-b534-c26f2ab82db5.png)

The duplicated key is `storybook/react-router-v6/story-loaded_0`. Could someone take a look on how to get rid of this warning/error? Thanks!

**Comment by JesusTheHun** [comment] 2023-03-24 18:06
Thank you for opening an issue. A new version is available to fix this issue, `v0.3.5`.
Can you confirm the issue is fixed on your side ?

**Comment by ningxie1991** [comment] 2023-03-24 21:49
Thanks for the quick fix. I just verified that this issue has been fixed and I don't see this warning anymore. Thanks!

**Closed** 2023-03-24 21:49 UTC
