### ISSUE TITLE
useParams cannot get routeParams as expected

### ISSUE THREAD

**Issue by iamyoki** [JesusTheHun/storybook-addon-react-router-v6#5] opened 2022-08-12 07:00 UTC
## Reproduce

```jsx
/** @type {import('@storybook/react').Meta} */
export default {
  component: PostDetail,
  parameters: {
    reactRouter: {
      routePath: '/posts/:postId',
      routeParams: {postId: 1},
    },
  },
};
export const Basic = (args) => {
  const {postId} = useParams();

  console.log(postId) // 👈 shows undefined in console

  return <PostDetailPage id={postId} />;
};
```

## Expected

react-router's `useParams` should get the corresponding value from `routeParams`.

**Comment by JesusTheHun** [comment] 2022-08-12 08:59
Hi 👋 Thank you for opening an issue.
I see you haven't declared the `decorator` property in the story, have you declared it somewhere else ?

**Comment by iamyoki** [comment] 2022-08-12 16:08
@JesusTheHun Oh! I forgot to mention that, I declared `decorator` in `preview.js` already.
```js
export const decorators = [
  withRouter,
  (Story) => (
    <SWRConfig value={{fetcher: request.get}}>
      <Global styles={[rebase, layout]} />
      <Story />
    </SWRConfig>
  ),
];
```

**Comment by JesusTheHun** [comment] 2022-08-14 05:45
Can you share a full reproduction example such as a repo ? Because I'm unable to reproduce the issue.

But just to be clear, is it normal that it is a story about `PostDetail`, but that the component is named `Basic` and renders `PostDetailPage` ?

**Comment by iamyoki** [comment] 2022-08-14 08:33
@JesusTheHun Thank you for answering.

You are very careful, it's normal in my source actually, here I just wrote wrong.

Please check out [my source code](https://github.com/QhlabTeam/cra-template-qhlab), and change [this line](https://github.com/QhlabTeam/cra-template-qhlab/blob/84a7adb15a6bd6e85c0ec28d51d30bfb3a0dfcc6/src/features/posts/PostDetail.stories.jsx#L11) into this
```jsx
export default {
  component: PostDetail,
  parameters: {
    reactRouter: {
      routePath: '/posts/:postId',
      routeParams: {postId: 1},
    },
  },
};

export const Basic = (args) => {
 const {id} = useParams()
  return  <PostDetail id={id} />
};
```

> Once you cloned and installed with yarn, use `yarn scripts` to start a storybook dev.

**Comment by JesusTheHun** [comment] 2022-08-14 10:04
I've taken a look and this is not an addon issue.
You cannot use a context (here the react router context) from story function.
If you move the `useParams()` inside a component you will get the expected parameter value.

For example, this will log the param value : 

```js
const LogParam = () => {
  const {postId} = useParams();
  console.log(postId);

  return null;
};

/** @type {import('@storybook/react').Story} */
export const Basic = (args) => {
  return (
    <>
      <LogParam />
      <PostDetail id='1' />
    </>
  );
};
```

I understand this is not what you were trying to achieve.
I suggest you use a wrapper to inject the parameters : 

```jsx
const InjectParam = ({params, children}) => {
  React.Children.only(children);

  const routeParams = useParams();
  const paramsToInject = {};

  params.forEach((param) => {
    if (typeof param === 'string') {
      paramsToInject[param] = routeParams[param];
      return;
    }

    const [routeParamName, propertyName] = param;
    paramsToInject[propertyName] = routeParams[routeParamName];
  });

  return React.cloneElement(children, paramsToInject);
};
```

```jsx
// Wrap your component inside your story function.

// <InjectParam params={['id']}> Using a simple string will map the `id` route param to the `id` property of the wrapper component.
// <InjectParam params={[['postId', 'id']]}> Using a tuple will map the `postId` route param to the `id` property.
// <InjectParam params={['anotherParam', ['postId', 'id']]}> You can mix both approaches

export const Basic = (args) => {
  return (
    <InjectParam params={[['postId', 'id']]}>
      <PostDetail />
    </InjectParam>
  );
};
```

**Comment by iamyoki** [comment] 2022-08-14 11:17
@JesusTheHun Thank you so much, it seems reasonable.

**Comment by JesusTheHun** [comment] 2022-08-14 11:34
If you consider your issue resolved, please close this issue.

**Closed** 2022-08-14 16:29 UTC
